### ISSUE TITLE
Put the container on the Hub?

### ISSUE THREAD

**Issue by amouat** [weaveworks/docker-plugin#28]
Unless you're holding back until things are more stable, it would be nice to have the plug-in image available from the Hub.

**Comment by squaremo** [comment]
Yeah fair enough -- there's no particular reason to make people compile it from scratch.

**Comment by Telmo** [comment]
any update on this?

**Comment by squaremo** [comment]
@Telmo I'll put an image up when #31 is merged (and I've checked there's no other show-stoppers)

**Comment by squaremo** [comment]
OK dokes, there's now a weaveworks/plugin:latest, which works with the docker nightly as of yesterday, on dockerhub.

**Comment by awh** [comment]
Closing as the plugin is now officially available in Weave Net 1.3.0.
