### ISSUE TITLE
Wrong default socket path for start-plugin.sh

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/docker-plugin#33]
`star-plugin.sh` maps `/run/docker/plugins` in `/usr/share/docker/plugins` but the default socket path is `/run/docker/plugins/weave.sock`, causing the container to fail with:

```
 /run/docker/plugins/weave.sock file not found
```

As a workaround you can invoke `start-plugin.sh` with `--socket=/usr/share/docker/plugins/weave.sock`

**Comment by awh** [comment]
start-plugin.sh is obsolete - functionality incorporated into weave script.
