### ISSUE TITLE
Make veth settings closer to those produced by the weave script

### ISSUE THREAD

**Issue by bboreham** [weaveworks/docker-plugin#53]
The `weave` script does a few things like `ethtool tx off` that the plugin doesn't currently do.

Most of these are not relevant to FDP, only the "slow" path.

**Comment by rade** [comment]
> Most of these are not relevant to FDP, only the "slow" path.

Such as?

The arp stuff is relevant to both.

**Comment by bboreham** [comment]
Well, `ethtool tx off` for one. Maybe "some" would be more defensible than "most".
